### Hello World 메시지를 반환하는 API 테스트
GET http://localhost:10080/hello-world
Accept: application/json

###
GET http://localhost:10080/hello-world-bean
Accept: application/json

###
GET http://localhost:10080/hello-world-bean/path-variable/1
Accept: application/json

###
GET http://localhost:10080/users
Accept: application/json

###
GET http://localhost:10080/users/1
Accept: application/json

###
GET http://localhost:10080/users/2
Accept: application/json

###
GET http://localhost:10080/users/4
Accept: application/json